[package]
name = "rust-opensea"
version = "0.1.0"
authors = ["akiho <aki030402@mail.com>"]
description = "OpenSea CLI"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3.1.6", features = ["derive"] }
dotenv = "0.15.0"
thiserror = "1.0.24"
bytes = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"
aws-config = "0.8.0"
aws-sdk-s3 = "0.8.0"
web3 = "0.17.0"
hex-literal = "0.3.4"
bigdecimal = "0.0.14"
regex = "1"
secp256k1 = "0.20.1"
reqwest = "0.11.10"