[package]
name = "rust-opensea"
version = "0.1.0"
authors = ["akiho <aki030402@mail.com>"]
description = "OpenSea CLI"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
clap = { version = "3.1.6", features = ["derive"] }