[package]
name = "impl_ethers_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
ethers = { version = "1.0.0", features = ["legacy"] }
ethers-signers = "1.0.0"
strum = "0.24.1"
strum_macros = "0.24.3"
thiserror = "1.0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.64"